name: Run E2E Tests # Nome do workflow

on: [pull_request] # quando executar esse CI (sempre que realizar um push para a repositório)

jobs:
  run-e2e-tests:  # nome do job
    name: Run E2E Tests
    runs-on: ubuntu-latest # Utilizar o sistema operacional unix

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: gympasares

    steps:
      - uses : actions/checkout@v3 # realizar o clone da aplicação
      - uses : actions/setup-node@v3 # instalar o node
        with:
          node-version: 18 # Especificar a versão do node
          cache: "npm" # cache das dependências para acelerar o processo de CI

      - run: npm ci # run executar comandos no terminal

      - run: npm run test:e2e
        env:
          BCRYPT_SALT: ${{ secrets.BCRYPT_SALT }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_URL: "postgresql://docker:docker@localhost:5432/gympasares?schema=public"




